### PR TITLE
SOE-2742: change CSS to look for youtube and vimeo

### PR DESCRIPTION
**Pull request by cjwest**
# READY FOR REVIEW

# Summary
- This adds a CSS check for youtube or vimeo before applying a height of 400px to an iFrame.

# Needed By (TBD)
- Next release

# Criticality
- Client is eagerly awaiting this.
- Fixes broken stuff

# Steps to Test
- Switch to this branch
- May need to clear caches
- ## Verify: 

Here's an example of a video page:
/magazine/article/wind-farms-can-be-tough-sell-residents-what-can-be-done

screen shot 2018-04-09 at 15 39 31

screen shot 2018-04-09 at 15 39 01

Here's an example of an audio page:
/magazine/article/debbie-senesky-developing-electronics-extremes-space

screen shot 2018-04-09 at 15 41 34

screen shot 2018-04-09 at 15 41 07

# Affects 
- SoE (School of Engineering website)

# Associated Issues and/or People
## Related JIRA ticket(s)
https://stanfordits.atlassian.net/browse/SOE-2742
https://stanfordits.atlassian.net/browse/SOE-2817

## Folks to notify
@minorwm

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by cjwest** [comment]
I'm just waiting to confirm that youtube and vimeo are the only hosting services we care about.

**Review by minorwm — CHANGES_REQUESTED** [review]
@cjwest this branch has conflicts and needs to be resolved.

**Comment by cjwest** [comment]
@minorwm,

I fixed the merge conflicts. I hope. Please review. Thanks!

**Review by minorwm — APPROVED** [review]

**Comment by minorwm** [comment]
@cjwest everything looks good. I'm merging this.

**Pull request merged**
