### PR TITLE
SOE-2492: Remove image style from og:image

### PR DESCRIPTION
**Pull request by kbrownell**
# READY FOR REVIEW

# Summary
- Tanja noticed that Facebook was not finding a default image for magazine articles.  It appears from testing, that when pointing Facebook towards a cached image style, it was indeed not able to find an image file.  Pointing Facebook to the original image, not a cached version, appears to reliably fix this issue.

# Needed By (12/6)

# Urgency
- It sounds like this is a blocker for Tanja's work.

# Steps to Test

1. This branch is checked out on dev and nobots have been disabled, so that Facebook can find and access Open Graph related metadata on the site.
2. Find a magazine article at https://sites.stanford.edu/jse-soe-dev/magazine.
3. On the magazine article page, click the "f" facebook share icon.  *But do not SHARE the dev page on your facebook account.*  Simply check that the image and article title, description load in the preview.  Please include a screenshot of this page in the comments below.  It should look like this.
screen shot 2017-12-06 at 11 37 05 am
4. Find a second article to test at https://sites.stanford.edu/jse-soe-dev/magazine.
5. Visit: https://developers.facebook.com/tools/debug/sharing and enter the magazine article URL you chose to test.
6. Click Debug and then click "Fetch new information" or "Scrape again" (depending on whether this particular page has been tested before).  If clicking "Scrape again", continue clicking it like 5-10 times until the "Time Scraped" date finally updates to a few seconds ago.
7. Even then, wait a few more seconds.  Then, scroll down and see whether the image, article title and description loaded in the preview.  Please include a screenshot of this in the comments below.  It should look something like this.
screen shot 2017-12-06 at 11 38 16 am

# Affected Projects or Products
- SOE's newsletter and site.

# Associated Issues and/or People
- https://stanfordits.atlassian.net/browse/SOE-2492
- @boznik

### CODE REVIEW

**Comment by cjwest** [comment]
Hi @kbrownell,

This looks like a default image:

screen shot 2017-12-06 at 12 58 43

After scraping:
screen shot 2017-12-06 at 13 02 26

screen shot 2017-12-06 at 13 21 39

from https://sites.stanford.edu/jse-soe-dev/magazine/article/jenny-suckale-better-plan-b-managing-disasters

**Comment by cjwest** [comment]
For: https://sites.stanford.edu/jse-soe-dev/magazine/article/pre-flight-simulations-ground-could-enhance-success-space
1) Clicked **Fetch new information**
2) Response:

screen shot 2017-12-06 at 13 36 00

3) Scrape again x6
screen shot 2017-12-06 at 13 38 35

**Comment by cjwest** [comment]
From https://sites.stanford.edu/jse-soe-dev/magazine/article/can-we-turn-tiny-amounts-waste-heat-thermoelectricity

1) I clicked the "f" facebook share icon:

screen shot 2017-12-06 at 13 44 20

**Comment by kbrownell** [comment]
@cjwest Thank you again so much.  Your previous notes were super helpful.  Can you try the following process:

1. This branch is checked out on dev and nobots have been disabled, so that Facebook can find and access Open Graph related metadata on the site.
2. Find a magazine article at https://sites.stanford.edu/jse-soe-dev/magazine.  Good test cases might include:
https://sites.stanford.edu/jse-soe-dev/magazine/article/does-autism-reflect-excitation-inhibition-imbalance-brain
https://sites.stanford.edu/jse-soe-dev/magazine/article/can-satellites-cause-artificial-eclipses-help-find-other-planets
(I haven't used them before and they don't have values in Meta tag.)
3. Edit the article and clear out any values, if there are any, in the Meta tag > Open Graph section at the bottom of the page.  Then save.
5. Visit: https://developers.facebook.com/tools/debug/sharing and enter the magazine article URL you chose to test.
6. Click Debug and then click "Fetch new information".
7. You should see the warning, "The provided 'og:image' properties are not yet available because new images are processed asynchronously. To ensure shares of new URLs include an image, specify the dimensions using 'og:image:width' and 'og:image:height' tags. Learn More".  If you don't see this warning, click "Scrape again" until you do.
8. Wait 10 minutes.
9. Click "Scrape again" until the "Time Scrapped" updates to a few seconds ago.  Then, scroll down and see whether the image, article title and description loaded in the preview.  If you see the warning, "Provided og:image URL, https://sites.stanford.edu/jse-soe-dev/sites/default/files/foesocialmedia.png could not be processed as an image. It may be corrupted or may have an invalid format."  Or the warning, "The 'og:image' property should be explicitly provided, even if a value can be inferred from other tags."  Keep clicking.  If you see a blank white space where the image should be; wait a few more seconds.  Please include a screenshot of this in the comments below.
3. On the magazine article page, click the "f" facebook share icon.  *But do not SHARE the dev page on your facebook account.*  Simply check that the image and article title, description load in the preview.  Please include a screenshot of this page in the comments below.  It should look like this.

**Comment by cjwest** [comment]
- Clicked **Scrape again** 6 times

screen shot 2017-12-06 at 17 06 43

- Clicked "f"

screen shot 2017-12-06 at 17 09 02

**Comment by cjwest** [comment]
- Clicked Scrape again 2 times. Did not wait 10 minutes.

screen shot 2017-12-06 at 17 17 06

- Clicked "f"

screen shot 2017-12-06 at 17 18 21

**Comment by kbrownell** [comment]
Ok.  Thank you for these checks as well!  I'm going to close this change and move further testing to the ticket, as this all points to facebook's scraping and not the image path, nor image styles.

**Pull request closed without merging**
