### PR TITLE
Soe 2236 refactored homepage featured events view

### PR DESCRIPTION
**Pull request by josephgknox**
# READY FOR REVIEW

# Summary
- Refactored homepage Featured Events view, changing markup, removing image, and re-styling as needed

# Needed By (Date)
- End of sprint (10/25)

# Urgency
- N/A

# Steps to Test

1. Pull this branch
2. Revert `stanford_soe_helper_event`
3. Verify that the homepage Feature Events block looks like mockup on ticket (InVision) or on related Google Doc (see links below)

# Affected Projects or Products
- stanford_soe_helper
- SOE

# Associated Issues and/or People
- https://stanfordits.atlassian.net/browse/SOE-2236
- https://projects.invisionapp.com/d/main#/console/10423578/254415347/inspect
- https://docs.google.com/document/d/1LCuqHA9ZTsnGlPDHz0hGI1A5GgJu6VMQrxMfJZNyUn8/edit#heading=h.s255r58sqqu3

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by kbrownell** [comment]
# Before
screen shot 2017-10-17 at 12 06 47 pm

# After (and logged out now)
screen shot 2017-10-17 at 12 07 09 pm

# Invision
screen shot 2017-10-17 at 12 06 32 pm

**Comment by kbrownell** [comment]
@josephgknox The calculated font size for this Event card looks a little smaller to me than the Invision app (18px v. 20px).  Do we care?  Is that outside the scope of what you're asking me to look at?

screen shot 2017-10-17 at 12 13 59 pm

**Comment by josephgknox** [comment]
@kbrownell good catch! Yeah, we've adjusted the font size from the comp upon implementing it on the web. Apologies for not including this detail. The font size is set to match that of the blocks next to it (DM and news), which have been specified for the web by Kerri.

**Comment by kbrownell** [comment]
Great!  Thanks for that information.  Merged.

**Pull request merged**
