### PR TITLE
SOEOP-366: Additional style changes as requested by client.

### PR DESCRIPTION
**Pull request by mdyoung3**
# READY FOR REVIEW

# Summary
- Some changes to the spacing on the news banner. Aligned the 

# Review By 
Today

# Criticality
Client wants it.

# Review Tasks

## Setup tasks and/or behavior to test

1. Clone into SOE local site setup.
2. Clear cache and check for text to be right aligned with header. See gif.

Screen Recording 2020-12-08 at 1 29 46 PM

# Associated Issues and/or People
- https://stanfordits.atlassian.net/jira/software/c/projects/SOEOP/issues/SOEOP-366

### CODE REVIEW

**Review by sherakama — APPROVED** [review]
The end result looks good but why all the negative margin? Normally when I see negatives it means something else is overzealous or wrong.

**Comment by boznik** [comment]
You meant left aligned, correct?

**Review by boznik — APPROVED** [review]
It does seem odd how much negative px are being used, but if it visually passes muster, i approve.

**Comment by mdyoung3** [comment]
@sherakama Good question.

Basically, it evolved that way. It made a little more sense when the header was the only element that required the negative left position. The other way would have required more overhaul of element structures. In addition, they're trying to mimic the magazine page: https://eng-stage.stanford.edu/magazine/article/marietje-schaake-can-democracy-survive-digital-world

As you can see, it has other elements not left aligned with header. So, I sort of felt that keeping the negative might be safer in case they choose to add more elements, to the banner. 

--Marc

**Comment by sherakama** [comment]
Thanks for documenting that. GTG.

**Pull request merged**
