### PR TITLE
Soe 3071 check solr

### PR DESCRIPTION
**Pull request by boznik**
# READY FOR REVIEW

# Summary
- Adding check for solr.

# Needed By (Date)
- Dynomite release

# Urgency
- Mild

# Steps to Test

1. Clone site to local
3. Check out this branch
2. Set solr index to read only
3. run cron
4. review dblog for Solr status

# Affected Projects or Products
- SOE

# Associated Issues and/or People
- https://stanfordits.atlassian.net/browse/SOE-3071

### CODE REVIEW

**Comment by jbickar** [comment]
"review dblog for Solr status" - what am I supposed to see?

**Comment by boznik** [comment]
This is almost ready, but not ready yet, when it's time to test, follow the steps to test.

**Comment by boznik** [comment]
ok this is ready for testing

**Review by minorwm — APPROVED** [review]
@boznik everything looks great to me. Working as written.

**Pull request merged**
