### PR TITLE
SOE-2318: Update CHANGELOG for 2.0-beta1 release

### PR DESCRIPTION
**Pull request by kbrownell**
# READY FOR REVIEW

# Summary
- This work spans the site’s public launch and includes a number of visual cleanup tasks, bug fixes, and enhancements to improve the categorization of information on pages.  For example, adding “Research & Ideas,” “School News,” and “Event” labels to featured content cards on the site homepage.

# Needed By (10/24)
- Today, so we can move forward with the push to production.

# Urgency
- Updating the CHANGELOG is not urgent, per se, but the PR is part of our process for tagging a new release and eventually moving the code live.

# Steps to Test

1. The purpose of this PR is really to approve the beta1 release.  In addition to the CHANGELOG and summary above, here are draft sections for the Release Notes:

```
Now what
You’ll need to revert the stanford_soe_helper_news
and stanford_soe_helper_event features for these 
changes to appear on production.

New Requirements and Risks
A fix to the vertical height of the Soundcloud 
embed requires stanford_magazine-7.x-1.0-beta1.

Diff (below)
```
[comparison of 7.x-2.0-alpha1 to proposed 7.x-2.0-beta1 release](https://github.com/su-soe/stanford_soe_helper/compare/be2df053b8f3471df70512783387158bf81c9805...88e8af15665b6323b9c2d10003db3781e88be480)

# Affected Projects or Products
- It affects the SOE school site, and components also in use on the Magazine, for example the Soundcloud height fix.

# Associated Issues and/or People
- [Full documentation of the release, including recent pull requests and ticket numbers.](https://docs.google.com/document/d/1aaIhPY7RCPjlse_GEW8IAzpLhM9mXsBtbJCQwInzm6U/edit#)

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by jbickar** [comment]
Can you update the versions in the `README.md` and all of the `.info` files as part of this PR? Then it can be merged and tagged.

**Comment by kbrownell** [comment]
Of course!  Yay, turns out this PR process was super useful.

**Comment by kbrownell** [comment]
Updated.  Thank you for the `sed` tip.  Here's what I used, in case I need to do this again later:

`find . -name "*.info" -exec sed -i '' 's/7.x-1.0-alpha1/7.x-2.0-beta1/g' "{}" \;` from the stanford_soe_helper/modules directory.

**Comment by jbickar** [comment]
My review process:

1. Check out this branch
2. Manually review the diff for anything, checking for anything that was *not* documentation or version related
3. Review the diff with `--name-only` to verify that only `CHANGELOG`, `README`, and `.info` files were modified
4. Recursively grep for ` 7.x-2.0-alpha1` to ensure that it was only found in `CHANGELOG`

**Pull request merged**
