### PR TITLE
SOEOP-366: Release Alpha 23.

### PR DESCRIPTION
**Pull request by mdyoung3**
# READY FOR REVIEW

# Summary
- Tag release for latest style changes. 

# Review By (Date)
ASAP

# Criticality
- 3/10

# Associated Issues and/or People
- https://stanfordits.atlassian.net/jira/software/c/projects/SOEOP/issues/SOEOP-366
- Latest changes: https://github.com/SU-SOE/stanford_soe_helper/commit/9f3d53d565eb6fc20e7a28ed448d31733681dc95

### CODE REVIEW

**Review by sherakama — CHANGES_REQUESTED** [review]
Changelog notice?

**Comment by mdyoung3** [comment]
@sherakama Dang. Missed adding it to the commit. 

It's committed now.

**Comment by sherakama** [comment]
commit and push? I don't see it.

**Comment by mdyoung3** [comment]
@sherakama Sorry. Not pushed. Having a weird issue.

**Comment by mdyoung3** [comment]
@sherakama Okay. It's pushed. Had to nuke my local and reedit the CHANGELOG it in order to push it.

**Review by sherakama — APPROVED** [review]
GTG

**Pull request merged**
